= Information about resources available on the network
:toc:
:toc-placement: manual

toc::[]

// Examples include download locations, ftp sites, web sites, and some
// information on network-specific programs.
// In the brave new Google world of effective searching, it may be somewhat
// less important than it was in the past.

== Email

Anyone may subscribe to the Computing Research Association's jobs@cra.org
list, but only organizations that advertise in Computing Research News may
post jobs announcements.
To Subscribe: Send the following mail message to listproc@cra.org:
                      subscribe jobs firstname lastname

Any username characters after "+" are ignored by mail delivery systems.
This makes it easy for me to add "+" suffices to simplify sorting of my
mail.

To obfuscate mailto email address links on web pages with Javascript to
avoid spam:  http://www.u.arizona.edu/~trw/spam/spam.htm
But this is probably hopeless:  your email address is probably out there
already, and you're probably using spam filtering already.

In Horde mail reader, I must create folders with names like
"INBOX.Daily", not "Daily" (which gives me "Permission denied" errors).

To join a Google Groups mailing list with a Google Apps account (e.g.,
@cs.washington.edu), you have to create your own URL:
  http://groups.google.com/group/_groupname_/boxsubscribe?email=_email_

In Google Groups, to permit "reply all" to go to the sender:
  Settings >> Email options >> Post replies: Users decide


== Source code repository hosting

For GitHub, to link directly to files in the repository, use rawgit.com.
Examples:
  https://rawgit.com/mernst/bibtex2web/master/bibtex2web.html
This does not seem to work for wiki files.

For Google Code, it is possible to link straight to HTML files in the
repository.  Examples:
  http://jsr308-langtools.googlecode.com/hg/doc/README-jsr308.html
  http://jsr308-langtools.googlecode.com/hg/doc/jsr308-changes.html
However, it's not convenient to link to files that are not in the
repository (such as a release or other generated files),
so it's generally better to put a project's webpages elsewhere.

Google code wiki syntax (a variant of MoinMoin syntax):
 * Don't break a bullet point across lines.
 * Don't break an external link (in square brackets) across lines.
 * For a table of contents, use
```
  Contents:
  <wiki:toc max_depth="1" />
```


== Uncategorized

LEDA is the Library of Efficient Data Types and Algorithms, implemented in C++.

The Forsythe list is a list of Ph.D.-granting Computer Science and Computer
Engineering Departments.

The dot/dotty tool is part of AT&T Research's graphviz package:
http://www.graphviz.org/
DaVinci is similar, but for X windows:
http://www.informatik.uni-bremen.de/~inform/forschung/daVinci/

(What is a comparison between xgrab and graphviz?)
'xgrab' (X graph browser), a graph layout and browser package running under
X11.R4, is available as cs.washington.edu:pub/xgrab.tar.Z.
Xgrab reads a textual specification of a graph, lays out the graph
using heuristics to minimize the number of edge crossings, and displays
the graph as labeled nodes and edges in an X window.  The user can then
edit the graph.  Once happy with the graph layout, xgrab can write a
postscript file or a text file describing the resulting graph.

ACM copyright form is available at
http://www.acm.org/pubs/copyright_form.html.

Phil Agre's "Designing Effective Action Alerts for the Internet" is
available at http://dlis.gseis.ucla.edu/people/pagre/alerts.html.  Point 15
is "Do not use a chain-letter petition."

To see whether a domain has been registered:
http://www.networksolutions.com/cgi-bin/whois/whois

SourceForge (http://sourceforge.net/) is a free open-source developer
support service that provides, among other things, CVS repositories and
access to compile farms.
Savannah is the GNU/FSF alternative.

Register domain names:  joker.com is cheap; also dotearth.com.

BSD calendar program:
// old: ftp://sunsite.unc.edu/pub/Linux/distributions/redhat/contrib/libc5/SRPMS/calendar-8.4-3.src.rpm
// old: ftp://metalab.unc.edu/pub/Linux/distributions/redhat/contrib/libc5/i386/calendar-8.4-3.i386.rpm
ftp://ftp.cs.uni-frankfurt.de/pub/linux/Mirror/ftp.redhat.com/contrib/libc5/SRPMS/calendar-8.4-3.src.rpm
Or, use "qalendar", but it doesn't permit comment lines.
Install:
```
  rpm -Uvh -vv ftp://ftp.cs.uni-frankfurt.de/pub/linux/Mirror/ftp.redhat.com/contrib/libc5/SRPMS/calendar-8.4-3.src.rpm
```

To donate used inkjet printer cartriges:  www.donateinkjets.com

The Elements of Style by Strunk and White is online (do a search for it).

NSF GPG (Grant Proposal Guide):
http://www.nsf.gov/pubs/2004/nsf042/nsf04_2.pdf

wget is a command-line utility to fetch web pages and save them to the
local disk.  http://www.gnu.org/software/wget/wget.html
To download a single file, only if it's newer than the on-disk version:
```
  wget -N URL
```
wget is also useful for web site mirroring.
To download everything below a current point:
```
  wget -r -k -np URL
```
To get just a single file and its dependencies, converted for local viewing:
```
  wget -pk -nH -nd -Pdownload-dir URL
```
Or, an easy way to do the latter is just to view the URL in Firefox, then
choose "save as"!

Andreas Zeller recommends EasyChair (www.easychair.org) as the best
conference management system he has used.
Many others recommend HotCRP, especially the systems community.

Paperdyne conference management system:
 * To view all abstracts, the key is to log in as reviewer (not PCC).
   Then, go to "Papers" and click "show abstracts' bodies".  (Click on
   "printer-friendly" version if printing.)
 * In Paperdyne the submission phase is not cloased automatically. 
   Paperdyne closes if you switch to the next phase (see 
   http://www.paperdyne.com/faq/p1_2.html).

VistaPrint.com: cheap business cards

Shimano road bicycle components, as explained by
http://www.epinions.com/content_957259908:
//nobreak

 * Sora
   Like the Deore mountain bike parts, the Sora is entry-level components.
 * Tiagra
   Like the LX side of Shimano.
 * 105
   The 105 component group is somewhere between an LX component group and
   an XT component group in the mountain biking division.
 * Ultegra
   This product line will be most comparable to the XT product line in the
   mountain division of Shimano.
 * Dura-Ace
   Like the XTR component group in the mountain bike division.

Buy clip art and photos:  http://istockphoto.com

When having networking problems in a Linux/Debian/Ubuntu VMware guest (e.g,
"no network connection" when hovering over icon), reinstall VMware tools.

To get a printable version of a blogger webblog, apply these diffs:
1:
```
   #content {
-    width:660px;
     margin:0 auto;
```
2:
```
   #main {
-    width:410px;
     float:left;
```

Web polls:
```
  doodle.com
  surveymonkey.com
```

// To run NetMeeting on Windows XP,
//   Start -> Run -> conf.exe

The plume-bib README instructions are available at
```
  http://plume-bib.googlecode.com/hg/README
```

For PC remote control:
//nobreak

 * logmein.com, 
 * If they are running Windows 7, its extremely easy to walk them through
    - Hitting the start button,
    - Typing 'Windows Remote Assistance' in the search bar
    - Clicking 'Invite someone you trust to help you,'
    - Clicking Easy Connect and having them recite the letters on their screen.
 * www.mikogo.com
 * teamviewer
 * ultraVNC single click
 * Meraki Systems Manager
 * Chrome Remote Desktop: https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp

For a Google spreadsheets survey, be sure to ask for repsondents' name,
because the user ID is not recorded by default.

For scheduling a meeting:
//nobreak

 * Doodle contains iCalendar integration (for $40/year).  WhenIsGood does not.
 * Doodle supports "if-need-be" responses.  WhenIsGood does not.
 * WhenIsGood's interface is far nicer.  With Doodle, you need to create
   many 30-minute proposals even to schedule a 1-hour meeting.  Each one
   takes multiple clicks to create and to answer.  Doodle just lets you
   quickly paint over the relevant times.
//nobreak

(Tungle.me combined the best of both, but it is no longer supported as of
December 3, 2012.)
Other possibilities, none of which seems great
/nobreak

 * Framadate: Not bad, but no calendar integration
 * Dudle:  by default gives just by-hour; slightly clunky interface.  No calendar integration
 * schedule once: has Google Calendar integration; $5+/month; not really for group meetings?
 * meetomatic.com: advanced is $20/year; without that, only per-day, not per-hour, control over times
 * gathergrid.com: only by hour; no calendar integration
 * whenshouldwe.com: terribly basic; not acceptable
 * selectthedate.com: selects a date, not among multiple times on one date

Briticizer:  http://us2uk.eu/
also: http://www.translatebritish.com/reverse.php

If someone asks a question whose answer can be easily Googled, you can supply them a link from the "Let me Google that for you" website, such as
http://lmgtfy.com/?q=UI+Chicago

To save a URL to Pocket, email one link at a time, in the body of mail to
add@getpocket.com.

Amazon Web Services (AWS) tips, from Darioush Jalali:
//nobreak

 * Billing is not logged by default. This can be confusing if you are
   trying to figure out how much money you are spending initially.
 * If you have jobs that can be restarted easily, spot instances are
 * up to 10x cheaper than on-demand instances. Amazon may turn them off
   whenever they choose (this is rare).
 * Amazon limits the number of types of certain instances they grant.
   Customer support will increase this, but it takes a couple days.
