= Information about resources available on the network
:toc:
:toc-placement: manual

toc::[]

// Examples include download locations, ftp sites, web sites, and some
// information on network-specific programs.
// In the brave new Google world of effective searching, it may be somewhat
// less important than it was in the past.

== Email

Anyone may subscribe to the Computing Research Association's jobs@cra.org
list, but only organizations that advertise in Computing Research News may
post jobs announcements.
To Subscribe: Send the following mail message to listproc@cra.org:
                      subscribe jobs firstname lastname

Any username characters after "+" are ignored by mail delivery systems.
This makes it easy for me to add "+" suffices to simplify sorting of my
mail.

To obfuscate mailto email address links on web pages with Javascript to
avoid spam:  http://www.u.arizona.edu/~trw/spam/spam.htm
But this is probably hopeless:  your email address is probably out there
already, and you're probably using spam filtering already.

In Horde mail reader, I must create folders with names like
"INBOX.Daily", not "Daily" (which gives me "Permission denied" errors).

To join a Google Groups mailing list with a Google Apps account (e.g.,
@cs.washington.edu), you have to create your own URL:
  http://groups.google.com/group/_groupname_/boxsubscribe?email=_email_

In Google Groups, to permit "reply all" to go to the sender:
  Settings >> Email options >> Post replies: Users decide

When creating a mailman mailing list, some common good options to change:
 * General options:
    * A terse phrase
    * Should Mailman replace any existing Message-ID: header: no
 * Membership Management >> Mass Subscription
 * Privacy options...
    * Sender filters
       * non-member addresses whose postings should be automatically accepted


== AWS Amazon Web services

To download files from Amazon S3, first install via
```
    sudo easy_install awscli
    aws configure
```
and then run a command such as
```
   aws s3 sync s3://bucketname .
```
For example:
```
   mkdir -p ~/tmp/aws-s3
   cd ~/tmp/aws-s3
   aws s3 sync s3://travis-checker-framework .
```
Doing `aws s3 sync s3://travis-checker-framework/typetools/checker-framework/1048/1048.1 .`
copies the contents of that remote directory to the current local directory.
To delete/remove files:
```
   aws s3 rm --recursive s3://travis-checker-framework/typetools
```

Amazon Web Services (AWS) tips, from Darioush Jalali:
//nobreak

 * Billing is not logged by default. This can be confusing if you are
   trying to figure out how much money you are spending initially.
 * If you have jobs that can be restarted easily, spot instances are
   up to 10x cheaper than on-demand instances. Amazon may turn them off
   whenever they choose (this is rare).
 * Amazon limits the number of types of certain instances they grant.
   Customer support will increase this, but it takes a couple days.


== Uncategorized

LEDA is the Library of Efficient Data Types and Algorithms, implemented in C++.

The Forsythe list is a list of Ph.D.-granting Computer Science and Computer
Engineering Departments.

The dot/dotty tool is part of AT&T Research's graphviz package:
http://www.graphviz.org/
DaVinci is similar, but for X windows:
http://www.informatik.uni-bremen.de/~inform/forschung/daVinci/

(What is a comparison between xgrab and graphviz?)
'xgrab' (X graph browser), a graph layout and browser package running under
X11.R4, is available as cs.washington.edu:pub/xgrab.tar.Z.
Xgrab reads a textual specification of a graph, lays out the graph
using heuristics to minimize the number of edge crossings, and displays
the graph as labeled nodes and edges in an X window.  The user can then
edit the graph.  Once happy with the graph layout, xgrab can write a
postscript file or a text file describing the resulting graph.

ACM copyright form is available at
http://www.acm.org/pubs/copyright_form.html.

Phil Agre's "Designing Effective Action Alerts for the Internet" is
available at http://dlis.gseis.ucla.edu/people/pagre/alerts.html.  Point 15
is "Do not use a chain-letter petition."

To see whether a domain has been registered:
http://www.networksolutions.com/cgi-bin/whois/whois

SourceForge (http://sourceforge.net/) is a free open-source developer
support service that provides, among other things, CVS repositories and
access to compile farms.
Savannah is the GNU/FSF alternative.

Register domain names:  joker.com is cheap; also dotearth.com.

BSD calendar program:
// old: ftp://sunsite.unc.edu/pub/Linux/distributions/redhat/contrib/libc5/SRPMS/calendar-8.4-3.src.rpm
// old: ftp://metalab.unc.edu/pub/Linux/distributions/redhat/contrib/libc5/i386/calendar-8.4-3.i386.rpm
ftp://ftp.cs.uni-frankfurt.de/pub/linux/Mirror/ftp.redhat.com/contrib/libc5/SRPMS/calendar-8.4-3.src.rpm
Or, use "qalendar", but it doesn't permit comment lines.
Install:
```
  rpm -Uvh -vv ftp://ftp.cs.uni-frankfurt.de/pub/linux/Mirror/ftp.redhat.com/contrib/libc5/SRPMS/calendar-8.4-3.src.rpm
```

To donate used inkjet printer cartriges:  www.donateinkjets.com

The Elements of Style by Strunk and White is online (do a search for it).

NSF GPG (Grant Proposal Guide):
http://www.nsf.gov/publications/pub_summ.jsp?ods_key=GPG

wget is a command-line utility to fetch web pages and save them to the
local disk.  http://www.gnu.org/software/wget/wget.html
To download a single file, only if it's newer than the on-disk version:
```
  wget -N URL
```
wget is also useful for web site mirroring.
To download everything below a current point:
```
  wget -r -k -np URL
```
To get just a single file and its dependencies, converted for local viewing:
```
  wget -pk -nH -nd -Pdownload-dir URL
```
Or, an easy way to do the latter is just to view the URL in Firefox, then
choose "save as"!

Andreas Zeller recommends EasyChair (www.easychair.org) as the best
conference management system he has used.
Many others recommend HotCRP, especially the systems community.

Paperdyne conference management system:
//nobreak

 * To view all abstracts, the key is to log in as reviewer (not PCC).
   Then, go to "Papers" and click "show abstracts' bodies".  (Click on
   "printer-friendly" version if printing.)
 * In Paperdyne the submission phase is not cloased automatically. 
   Paperdyne closes if you switch to the next phase (see 
   http://www.paperdyne.com/faq/p1_2.html).

VistaPrint.com: cheap business cards

Shimano road bicycle components, as explained by
http://www.epinions.com/content_957259908:
//nobreak

 * Sora
   Like the Deore mountain bike parts, the Sora is entry-level components.
 * Tiagra
   Like the LX side of Shimano.
 * 105
   The 105 component group is somewhere between an LX component group and
   an XT component group in the mountain biking division.
 * Ultegra
   This product line will be most comparable to the XT product line in the
   mountain division of Shimano.
 * Dura-Ace
   Like the XTR component group in the mountain bike division.

Buy clip art and photos:  http://istockphoto.com

When having networking problems in a Linux/Debian/Ubuntu VMware guest (e.g,
"no network connection" when hovering over icon), reinstall VMware tools.

To get a printable version of a blogger webblog, apply these diffs:
1:
```
   #content {
-    width:660px;
     margin:0 auto;
```
2:
```
   #main {
-    width:410px;
     float:left;
```

// To run NetMeeting on Windows XP,
//   Start -> Run -> conf.exe

The plume-bib README instructions are available at
```
  http://rawgit.com/mernst/plume-bib/master/README
  https://rawgit.com/mernst/plume-bib/master/README
  https://raw.githubusercontent.com/mernst/plume-bib/master/README
```
the latter two of which are identical.

Neither of these redirect:
```
  http://rawgit.com/mernst/randoop/master/doc/index.html
  https://rawgit.com/mernst/randoop/master/doc/index.html
```
even though the second one of these two does redirect:
```
  http://rawgit.com/mernst/plume-bib/master/README
  https://rawgit.com/mernst/plume-bib/master/README
```
Weird.

For PC remote control:
//nobreak

 * logmein.com, 
 * If they are running Windows 7, its extremely easy to walk them through
    - Hitting the start button,
    - Typing 'Windows Remote Assistance' in the search bar
    - Clicking 'Invite someone you trust to help you,'
    - Clicking Easy Connect and having them recite the letters on their screen.
 * www.mikogo.com
 * teamviewer
 * ultraVNC single click
 * Meraki Systems Manager
 * Chrome Remote Desktop: https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp

For a Google spreadsheets survey, be sure to ask for repsondents' name,
because the user ID is not recorded by default.

Web polls:
```
  doodle.com
  surveymonkey.com
```

For scheduling a meeting:
//nobreak

 * Doodle contains iCalendar integration (for $40/year).  WhenIsGood/When2Meet does not.
 * Doodle supports "if-need-be" (ifneedbe) responses.  WhenIsGood premium has this.
   When2Meet does not.  
 * WhenIsGood/When2Meet has a nicer interface.  With Doodle, you need to create
   many 30-minute proposals even to schedule a 1-hour meeting.  Each one
   takes multiple clicks to create and to answer.  WhenIsGood/When2Meet just lets you
   quickly paint over the relevant times.
 * WhenIsGood has accounts.  When2Meet does not.
//nobreak

(Tungle.me combined the best of both, but it is no longer supported as of
December 3, 2012.)
Other possibilities, none of which seems great
/nobreak

 * Framadate: Not bad, but no calendar integration
 * Dudle:  by default gives just by-hour; slightly clunky interface.  No calendar integration
 * schedule once: has Google Calendar integration; $5+/month; not really for group meetings?
 * meetomatic.com: advanced is $20/year; without that, only per-day, not per-hour, control over times
 * gathergrid.com: only by hour; no calendar integration
 * whenshouldwe.com: terribly basic; not acceptable
 * selectthedate.com: selects a date, not among multiple times on one date

Two tips about Doodle polls:
//nobreak

 * For a 1-hour meeting, give 30-minute timeslots.  That lets participants  communicate that they could make 1:30-2:30 but not 1-2 or 2-3.  It's especially important at UW since standard classes start on the half hour.
 * Consider permitting "if-need-be" as a response.  It can give more scheduling flexibiliity.

Briticizer:  http://us2uk.eu/
also: http://www.translatebritish.com/reverse.php

If someone asks a question whose answer can be easily Googled, you can supply them a link from the "Let me Google that for you" website, such as
http://lmgtfy.com/?q=UI+Chicago

To save a URL to Pocket, email one link at a time, in the body of mail to
add@getpocket.com.

Trello is a popular task management system (a to-do list).  I don't see
what makes it compelling, though.  It doesn't support the most important
things that I want to do, such as sorting items, seeing an overview of all
the issues, integrating with my existing toolchain (version control system,
editor, etc.), working offline, etc.

Coveralls (https://coveralls.io/) reports test coverage.
For Java, it requires Maven.

Code review tools:
GitHub pull requests: not terrible
RBCommons (OK, but not enough better than GitHub pull requests that it is worth money)
Phabricator: some people rave about it.
  It can integrate with shipshape, the open-source version of tricorder.
  Code Reviews with Phabricator: 
   * The tool to create and review patches in Phabricator is called Differential.
   * Phabricator has a tool called Arcanist to upload patches from the command line. To get you set up, follow the Arcanist Quick Start instructions.
  Phabricator hosting:
   * paid hosting, from the creators: phacility.com
   * Free Phabricator hosting (for open source, cheap otherwise): phoreplay.com
   * Cloudpipes: Integrate GitHub with Phabricator (in invite-only beta as of
     5/2015 and 7/6/2015).  https://www.cloudpipes.com/invite
Gerrit (https://www.gerritcodereview.com/) doesn't seem like as good a choice:
  some people say it has an UI, and it isn't as widely used.  There is GitHub integration:  http://gerrithub.io/
Reviewable: https://reviewable.io.  Gives me the creeps because they put
  people's quotes on their webpage as if they are endorsements, when those
  quotes are from people who never used Reviewable.

To search for source code (in approximate order of preference):
 * SearchCode
 * GitHub search
 * http://code.openhub.net/ (was Koders.com; by Black Duck)

To avoid waiting on hold:
http://www.lucyphone.com/
http://www.fastcustomer.co/mf

Outsourcing companies (I have no particular reason to prefer one over the other):
 * Freelancer (was vWorker)
 * oDesk (Panos Ipeirotis is on sabbatical there)
 * Elance
 * others? TaskRabbit, Guru, TopCoder, Craigslist, rentacoder
For designs: 99designs.com, dribbble.com
Advice on hiring: https://news.ycombinator.com/item?id=2539892 .  Key: ask
a simple domain-knowledge type question in the posting, or how they would
go about the project. Ask for references. Ask them to restate what you want,
in their own words. Do a Skype interview. Be
willing to pay (say, $50/hour instead of $25). Give a small test
project before moving forward. Hire multiple people for that first project.
Say there may be more work after the initial bit.
http://www.keithmander.com/?p=243 says:
 * Use uTest to perform QA of the code.
 * Always make sure you have a clear agreement in place that spells out how owns the finished output and what the rights are for the contractor.

Creating a new Maven Central ("the Central Repository") project:
http://central.sonatype.org/pages/ossrh-guide.html
Example issues:
https://issues.sonatype.org/browse/OSSRH-28628
https://issues.sonatype.org/browse/OSSRH-37810

SPL (Seattle Public Library) suggestions for purchane:
https://www.spl.org/library-collection/suggestions-for-purchase/purchase-suggestion-form-for-books-and-music-scores

SPL (Seattle Public Library) access to Consumer Reports and more databases:
http://www.spl.org/library-collection/articles-and-research/databases-a-z

A tip about combining sections in Canvas.
Suppose in your Canvas Dashboard (canvas.uw.edu) you see
- multiple Canvas "courses" as CSE XXX A  Sp 18,  CSE XXX B Sp18, CSE 
XXX C Sp18, each of which has multiple sections, AA, AB, BA, BB, CA, CB.
- or a cross-listed course with two "courses" CSE XXX A Sp 18 and CSEM 
XXX A Sp18.
 +
1.  Select one of these from your Dashboard and click on it.  You are 
going to use this one as the "home course" where all the other sections 
are moved to.
2. Look at the URL for this page 
"https://canvas.uw.edu/courses/YYYYYYYY" and copy the "YYYYYYYY" 
number.  This is the Canvas "ID" that you will use to copy things into 
this "home course".
3.  On the very bottom left just to the right of the purple column click 
on "Settings".  This will bring up the "Course Details" tab for that 
"course".   Change the "Name" field to whatever name you that you think 
covers all the sections of your course in Canvas.  (You can also change 
the "Course Code" field if you want; I am not sure if it matters.   You 
can't change the SIS ID but you don't need to.)
4.  Now go to the Canvas Dashboard and click on one of the *other* 
Canvas "courses" associated with your course.
5. On the very bottom left just to the right of the purple column click 
on "Settings".  This will bring up the "Course Details" tab for that 
"course" as before.
6. Click on the "Sections" tab near the top of the page to list the 
sections.  This will list all sections of this *other* course.
7.  Click on one of these sections, which will bring up a list of 
current enrollees.   At the right side of the page then click on 
"Cross-List this Section".  This will be bring up a dialog box. Enter 
the Canvas ID "YYYYYYYY" number which you copied from step 2, in the ID 
field of this box.   It will bring up the name of the "home course".   
Then click that you accept this.  This will cause your section to jump 
to the "home course" and your view will be teleported to the inside of 
the "home course".
8. Go back to your Canvas Dashboard.
 +
If *other* Canvas "courses" associated with your course still show up 
then they still have sections that you haven't moved so go back to Step 4.
If all of their sections have been moved then the Canvas courses will 
have disappeared from your Dashboard.   Do one final check via 
"Settings" on your "home course" and the "Sections" tab to make sure 
that everything is there.  If so, you are done!

I don't have permission to edit the calendar event (in Google Calendar).  I personally use this Chrome extension to make that the default
https://chrome.google.com/webstore/detail/google-calendar-guests-mo/hjhicmeghjagaicbkmhmbbnibhbkcfdb?hl=en

Charlie Garrett's perferred C++ references:
The C++ Standard Library by Josuttis
C++ Templates by Vandevoorde, Josuttis and Gregor
C++ for the Impatient by Overland

Cloud credits for research from AWS and EC2, for experiments:
https://aws.amazon.com/research-credits/

To import an ical file into Google Calendar:
https://support.google.com/calendar/answer/37118?co=GENIE.Platform%3DDesktop&hl=en&oco=0
