= Information about resources available on the network
:toc:
:toc-placement: manual

toc::[]

// Examples include download locations, ftp sites, web sites, and some
// information on network-specific programs.
// In the brave new Google world of effective searching, it may be somewhat
// less important than it was in the past.

== Email

Anyone may subscribe to the Computing Research Association's jobs@cra.org
list, but only organizations that advertise in Computing Research News may
post jobs announcements.
To Subscribe: Send the following mail message to listproc@cra.org:
                      subscribe jobs firstname lastname

Any username characters after "+" are ignored by mail delivery systems.
This makes it easy for me to add "+" suffices to simplify sorting of my
mail.

To obfuscate mailto email address links on web pages with Javascript to
avoid spam:  http://www.u.arizona.edu/~trw/spam/spam.htm
But this is probably hopeless:  your email address is probably out there
already, and you're probably using spam filtering already.

In Horde mail reader, I must create folders with names like
"INBOX.Daily", not "Daily" (which gives me "Permission denied" errors).

To join a Google Groups mailing list with a Google Apps account (e.g.,
@cs.washington.edu), you have to create your own URL:
  http://groups.google.com/group/_groupname_/boxsubscribe?email=_email_

In Google Groups, to permit "reply all" to go to the sender:
  Settings >> Email options >> Post replies: Users decide


== Uncategorized

LEDA is the Library of Efficient Data Types and Algorithms, implemented in C++.

The Forsythe list is a list of Ph.D.-granting Computer Science and Computer
Engineering Departments.

The dot/dotty tool is part of AT&T Research's graphviz package:
http://www.graphviz.org/
DaVinci is similar, but for X windows:
http://www.informatik.uni-bremen.de/~inform/forschung/daVinci/

(What is a comparison between xgrab and graphviz?)
'xgrab' (X graph browser), a graph layout and browser package running under
X11.R4, is available as cs.washington.edu:pub/xgrab.tar.Z.
Xgrab reads a textual specification of a graph, lays out the graph
using heuristics to minimize the number of edge crossings, and displays
the graph as labeled nodes and edges in an X window.  The user can then
edit the graph.  Once happy with the graph layout, xgrab can write a
postscript file or a text file describing the resulting graph.

ACM copyright form is available at
http://www.acm.org/pubs/copyright_form.html.

Phil Agre's "Designing Effective Action Alerts for the Internet" is
available at http://dlis.gseis.ucla.edu/people/pagre/alerts.html.  Point 15
is "Do not use a chain-letter petition."

To see whether a domain has been registered:
http://www.networksolutions.com/cgi-bin/whois/whois

SourceForge (http://sourceforge.net/) is a free open-source developer
support service that provides, among other things, CVS repositories and
access to compile farms.
Savannah is the GNU/FSF alternative.

Register domain names:  joker.com is cheap; also dotearth.com.

BSD calendar program:
// old: ftp://sunsite.unc.edu/pub/Linux/distributions/redhat/contrib/libc5/SRPMS/calendar-8.4-3.src.rpm
// old: ftp://metalab.unc.edu/pub/Linux/distributions/redhat/contrib/libc5/i386/calendar-8.4-3.i386.rpm
ftp://ftp.cs.uni-frankfurt.de/pub/linux/Mirror/ftp.redhat.com/contrib/libc5/SRPMS/calendar-8.4-3.src.rpm
Or, use "qalendar", but it doesn't permit comment lines.
Install:
```
  rpm -Uvh -vv ftp://ftp.cs.uni-frankfurt.de/pub/linux/Mirror/ftp.redhat.com/contrib/libc5/SRPMS/calendar-8.4-3.src.rpm
```

To donate used inkjet printer cartriges:  www.donateinkjets.com

The Elements of Style by Strunk and White is online (do a search for it).

NSF GPG (Grant Proposal Guide):
http://www.nsf.gov/publications/pub_summ.jsp?ods_key=GPG

wget is a command-line utility to fetch web pages and save them to the
local disk.  http://www.gnu.org/software/wget/wget.html
To download a single file, only if it's newer than the on-disk version:
```
  wget -N URL
```
wget is also useful for web site mirroring.
To download everything below a current point:
```
  wget -r -k -np URL
```
To get just a single file and its dependencies, converted for local viewing:
```
  wget -pk -nH -nd -Pdownload-dir URL
```
Or, an easy way to do the latter is just to view the URL in Firefox, then
choose "save as"!

Andreas Zeller recommends EasyChair (www.easychair.org) as the best
conference management system he has used.
Many others recommend HotCRP, especially the systems community.

Paperdyne conference management system:
//nobreak

 * To view all abstracts, the key is to log in as reviewer (not PCC).
   Then, go to "Papers" and click "show abstracts' bodies".  (Click on
   "printer-friendly" version if printing.)
 * In Paperdyne the submission phase is not cloased automatically. 
   Paperdyne closes if you switch to the next phase (see 
   http://www.paperdyne.com/faq/p1_2.html).

VistaPrint.com: cheap business cards

Shimano road bicycle components, as explained by
http://www.epinions.com/content_957259908:
//nobreak

 * Sora
   Like the Deore mountain bike parts, the Sora is entry-level components.
 * Tiagra
   Like the LX side of Shimano.
 * 105
   The 105 component group is somewhere between an LX component group and
   an XT component group in the mountain biking division.
 * Ultegra
   This product line will be most comparable to the XT product line in the
   mountain division of Shimano.
 * Dura-Ace
   Like the XTR component group in the mountain bike division.

Buy clip art and photos:  http://istockphoto.com

When having networking problems in a Linux/Debian/Ubuntu VMware guest (e.g,
"no network connection" when hovering over icon), reinstall VMware tools.

To get a printable version of a blogger webblog, apply these diffs:
1:
```
   #content {
-    width:660px;
     margin:0 auto;
```
2:
```
   #main {
-    width:410px;
     float:left;
```

Web polls:
```
  doodle.com
  surveymonkey.com
```

// To run NetMeeting on Windows XP,
//   Start -> Run -> conf.exe

The plume-bib README instructions are available at
```
  http://rawgit.com/mernst/plume-bib/master/README
  https://rawgit.com/mernst/plume-bib/master/README
  https://raw.githubusercontent.com/mernst/plume-bib/master/README
```
the latter two of which are identical.

Neither of these redirect:
```
  http://rawgit.com/mernst/randoop/master/doc/index.html
  https://rawgit.com/mernst/randoop/master/doc/index.html
```
even though the second one of these two does redirect:
```
  http://rawgit.com/mernst/plume-bib/master/README
  https://rawgit.com/mernst/plume-bib/master/README
```
Weird.

For PC remote control:
//nobreak

 * logmein.com, 
 * If they are running Windows 7, its extremely easy to walk them through
    - Hitting the start button,
    - Typing 'Windows Remote Assistance' in the search bar
    - Clicking 'Invite someone you trust to help you,'
    - Clicking Easy Connect and having them recite the letters on their screen.
 * www.mikogo.com
 * teamviewer
 * ultraVNC single click
 * Meraki Systems Manager
 * Chrome Remote Desktop: https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp

For a Google spreadsheets survey, be sure to ask for repsondents' name,
because the user ID is not recorded by default.

For scheduling a meeting:
//nobreak

 * Doodle contains iCalendar integration (for $40/year).  WhenIsGood does not.
 * Doodle supports "if-need-be" responses.  WhenIsGood does not.
 * WhenIsGood's interface is far nicer.  With Doodle, you need to create
   many 30-minute proposals even to schedule a 1-hour meeting.  Each one
   takes multiple clicks to create and to answer.  Doodle just lets you
   quickly paint over the relevant times.
//nobreak

(Tungle.me combined the best of both, but it is no longer supported as of
December 3, 2012.)
Other possibilities, none of which seems great
/nobreak

 * Framadate: Not bad, but no calendar integration
 * Dudle:  by default gives just by-hour; slightly clunky interface.  No calendar integration
 * schedule once: has Google Calendar integration; $5+/month; not really for group meetings?
 * meetomatic.com: advanced is $20/year; without that, only per-day, not per-hour, control over times
 * gathergrid.com: only by hour; no calendar integration
 * whenshouldwe.com: terribly basic; not acceptable
 * selectthedate.com: selects a date, not among multiple times on one date

Briticizer:  http://us2uk.eu/
also: http://www.translatebritish.com/reverse.php

If someone asks a question whose answer can be easily Googled, you can supply them a link from the "Let me Google that for you" website, such as
http://lmgtfy.com/?q=UI+Chicago

To save a URL to Pocket, email one link at a time, in the body of mail to
add@getpocket.com.

Amazon Web Services (AWS) tips, from Darioush Jalali:
//nobreak

 * Billing is not logged by default. This can be confusing if you are
   trying to figure out how much money you are spending initially.
 * If you have jobs that can be restarted easily, spot instances are
 * up to 10x cheaper than on-demand instances. Amazon may turn them off
   whenever they choose (this is rare).
 * Amazon limits the number of types of certain instances they grant.
   Customer support will increase this, but it takes a couple days.

Trello is a popular task management system (a to-do list).  I don't see
what makes it compelling, though.  It doesn't support the most important
things that I want to do, such as sorting items, seeing an overview of all
the issues, integrating with my existing toolchain (version control system,
editor, etc.), working offline, etc.

Coveralls (https://coveralls.io/) reports test coverage.
For Java, it requires Maven.

To convert Markdown to HTML:
(query-replace-regexp "\\[\\([^]]*\\)\\](\\([^)]*\\)" "<a href=\"\\2\">\\1</a>"))

Code review tools:
GitHub pull requests: not terrible
RBCommons (OK, but not enough better than GitHub pull requests that it is worth money)
Phabricator: some people rave about it.
  It can integrate with shipshape, the open-source version of tricorder.
  Code Reviews with Phabricator: 
   * The tool to create and review patches in Phabricator is called Differential.
   * Phabricator has a tool called Arcanist to upload patches from the command line. To get you set up, follow the Arcanist Quick Start instructions.
  Phabricator hosting:
   * paid hosting, from the creators: phacility.com
   * Free Phabricator hosting (for open source, cheap otherwise): phoreplay.com
   * Cloudpipes: Integrate GitHub with Phabricator (in invite-only beta as of
     5/2015 and 7/6/2015).  https://www.cloudpipes.com/invite
Gerrit (https://www.gerritcodereview.com/) doesn't seem like as good a choice:
  some people say it has an UI, and it isn't as widely used.  There is GitHub integration:  http://gerrithub.io/
Reviewable: https://reviewable.io.  Gives me the creeps because they put
  people's quotes on their webpage as if they are endorsements, when those
  quotes are from people who never used Reviewable.

Whitelist of Ubuntu packages that can can be installed on container-based
Travis-CI infrastructure using the APT addon mechanism:
https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
(which is linked from https://github.com/travis-ci/apt-package-whitelist)

Travis-CI advantages:
 * no local sysadmin
 * setup is checked into the version control repository
 * builds pull requests and branches as well as the mainline
 * every user can enable it for their repositories and forks
Travis-CI disadvantages:
 * old OS:
    * default build infrastructure is Ubuntu 12.04
    * no OS more recent than Ubuntu 14.04 is available
    * these OS limitations are shared by other cloud CI infrastructure
 * time limits:
    * jobs are limited to less than 2 hours
    * for Ubuntu 14.04, jobs are limited to about 50 minutes
    * if a repository has been tested a lot recently, new builds may be delayed
 * memory limits:
    * machines have only 3-7 GB of memory; Java only uses 1/4 of this for its
      maximum heap size; so I sometimes need -Xmx2500M command-line argument
 * no way to ssh in to virtual machines, which complicates debugging

A commit that has `[ci skip]` anywhere in the commit message is ignored by
Travis CI -- Travis does not run the continuous integration build/test
for that commit.

To download files from Amazon S3, first install via
```
    sudo easy_install awscli
    aws configure
```
and then run a command such as
```
   aws s3 sync s3://bucketname .
```
